export class CurrencyUtil {
    // Comprehensive map of currency codes to symbols
    private static symbolOverrides: Record<string, string> = {
        'AED': 'د.إ',
        'AFN': '؋',
        'ALL': 'L',
        'AMD': '֏',
        'ANG': 'ƒ',
        'AOA': 'Kz',
        'ARS': '$',
        'AUD': '$',
        'AWG': 'ƒ',
        'AZN': '₼',
        'BAM': 'KM',
        'BBD': '$',
        'BDT': '৳',
        'BGN': 'лв',
        'BHD': '.د.ب',
        'BIF': 'FBu',
        'BMD': '$',
        'BND': '$',
        'BOB': 'Bs.',
        'BRL': 'R$',
        'BSD': '$',
        'BTC': '₿',
        'BTN': 'Nu.',
        'BWP': 'P',
        'BYN': 'Br',
        'BZD': 'BZ$',
        'CAD': '$',
        'CDF': 'FC',
        'CHF': 'CHF',
        'CLP': '$',
        'CNY': '¥',
        'COP': '$',
        'CRC': '₡',
        'CUC': '$',
        'CUP': '₱',
        'CVE': '$',
        'CZK': 'Kč',
        'DJF': 'Fdj',
        'DKK': 'kr',
        'DOP': 'RD$',
        'DZD': 'دج',
        'EGP': '£',
        'ERN': 'Nfk',
        'ETB': 'Br',
        'EUR': '€',
        'FJD': '$',
        'FKP': '£',
        'GBP': '£',
        'GEL': '₾',
        'GGP': '£',
        'GHS': 'GH₵',
        'GIP': '£',
        'GMD': 'D',
        'GNF': 'FG',
        'GTQ': 'Q',
        'GYD': '$',
        'HKD': '$',
        'HNL': 'L',
        'HRK': 'kn',
        'HTG': 'G',
        'HUF': 'Ft',
        'IDR': 'Rp',
        'ILS': '₪',
        'IMP': '£',
        'INR': '₹',
        'IQD': 'ع.د',
        'IRR': '﷼',
        'ISK': 'kr',
        'JEP': '£',
        'JMD': 'J$',
        'JOD': 'د.ا',
        'JPY': '¥',
        'KES': 'KSh',
        'KGS': 'с',
        'KHR': '៛',
        'KMF': 'CF',
        'KPW': '₩',
        'KRW': '₩',
        'KWD': 'د.ك',
        'KYD': '$',
        'KZT': '₸',
        'LAK': '₭',
        'LBP': 'ل.ل',
        'LKR': '₨',
        'LRD': '$',
        'LSL': 'L',
        'LYD': 'ل.د',
        'MAD': 'د.م.',
        'MDL': 'L',
        'MGA': 'Ar',
        'MKD': 'ден',
        'MMK': 'K',
        'MNT': '₮',
        'MOP': 'MOP$',
        'MRU': 'UM',
        'MUR': '₨',
        'MVR': 'Rf',
        'MWK': 'MK',
        'MXN': '$',
        'MYR': 'RM',
        'MZN': 'MT',
        'NAD': '$',
        'NGN': '₦',
        'NIO': 'C$',
        'NOK': 'kr',
        'NPR': '₨',
        'NZD': '$',
        'OMR': 'ر.ع.',
        'PAB': 'B/.',
        'PEN': 'S/',
        'PGK': 'K',
        'PHP': '₱',
        'PKR': '₨',
        'PLN': 'zł',
        'PYG': 'Gs',
        'QAR': 'ر.ق',
        'RON': 'lei',
        'RSD': 'дин.',
        'RUB': '₽',
        'RWF': 'FRw',
        'SAR': 'ر.س',
        'SBD': '$',
        'SCR': '₨',
        'SDG': 'ج.س.',
        'SEK': 'kr',
        'SGD': '$',
        'SHP': '£',
        'SLL': 'Le',
        'SOS': 'S',
        'SRD': '$',
        'SSP': '£',
        'STN': 'Db',
        'SYP': '£',
        'SZL': 'L',
        'THB': '฿',
        'TJS': 'ЅM',
        'TMT': 'm',
        'TND': 'د.ت',
        'TOP': 'T$',
        'TRY': '₺',
        'TTD': 'TT$',
        'TVD': '$',
        'TWD': 'NT$',
        'TZS': 'TSh',
        'UAH': '₴',
        'UGX': 'USh',
        'USD': '$',
        'UYU': '$U',
        'UZS': 'лв',
        'VES': 'Bs.S',
        'VND': '₫',
        'VUV': 'VT',
        'WST': 'T',
        'XAF': 'FCFA',
        'XCD': '$',
        'XOF': 'CFA',
        'XPF': '₣',
        'YER': '﷼',
        'ZAR': 'R',
        'ZMW': 'ZK',
        'ZWL': '$'
    };

    static getSymbol(currencyCode: string): string {
        const code = currencyCode.toUpperCase();
        if (this.symbolOverrides[code]) {
            return this.symbolOverrides[code];
        }

        // Fallback to Intl if not in our map (though our map is very comprehensive)
        try {
            const parts = new Intl.NumberFormat('en-US', {
                style: 'currency',
                currency: code,
            }).formatToParts(0);
            return parts.find((part) => part.type === 'currency')?.value || code;
        } catch (e) {
            return code;
        }
    }
}
